version: '3'

services:
  api:
   image: api_server:0.1
   container_name: api_server
   command: /home/node/src/api_server.js
   volumes:
     - ./api_server/src:/home/node/src
  web:
   image: http_server:0.1
   container_name: http_server
   command: /home/http_server_user/src/http_server.py
   volumes:
     - ./http_server/src:/home/http_server_user/src
   ports:
     - 8080:8888
   environment:
     - API_SERVER_URL=http://api:12345

